class ItemAlreadyExistsError(Exception):
    pass

class NotFoundError(Exception):
    pass